### ISSUE TITLE
Unable to Initialize Steam API

### ISSUE THREAD

**Issue by CodeOfTheRing** [Dealman/BannerlordModTemplate#1]
Whenever I try to run the game from VS with the debugger it says failed to initialize steam API. I have a legit copy on steam.

**Comment by Dealman** [comment]
Hmm, does it set the directories properly?

**Comment by CodeOfTheRing** [comment]
Yeah I've tried like 3-4 times myself this program anything. Guides. I just can't seem to launch the game with VS.

**Comment by Dealman** [comment]
Could you please provide me with the paths it automatically generated for you? Some other potential fixes;

Try temporarily disabling any anti-virus and the firewall, try launching Visual Studio as administrator.

Is Steam running?

**Comment by CodeOfTheRing** [comment]
have to run vs as admin thanks buddy.
