### ISSUE TITLE
Copy All Files to Module Folder

### ISSUE THREAD

**Issue by RalfKeller** [Dealman/BannerlordModTemplate#2]
It seems like online the DLL is copied to the modules folder. I added a XML-File to the Project, set "copy to build directory" to "always", but I still have to manually copy the XML-File to the Modules folder. It would be nice if this could also happen automatically.

**Comment by Dealman** [comment]
Go to your project's properties and under the Build Events tab you can see how I copy the SubModule.xml. You should be able to use that if you want any other files to be moved as well.

For example;
`xcopy /d /y "$(MSBuildProjectDirectory)\Config\MyConfig.xml" "C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\MyMod\ModuleData"`

/d - indicates it will only copy if the file being copied is newer
/y - whether or not to overwrite if a file already exists

**Comment by RalfKeller** [comment]
Thank you, that helps a lot!
