### ISSUE TITLE
Use all actived mods as start argument

### ISSUE THREAD

**Issue by RalfKeller** [Dealman/BannerlordModTemplate#3]
In my heavily modded game it is not possible to load my safegame without all the mods that I normally use. I have to manually add all my activated mods to the debugging-arguments. It would be nice if this could happen automatically.

**Comment by Dealman** [comment]
This should be possible to add. One way would be to read the LauncherData.xml file and add all those that are listed as IsSelected.

Would this be what you want?

**Comment by Dealman** [comment]
Support for this was added with c5281ef674936ec8e68edd4fca2c3c87ec6085f3. Available in [V1.1.0](https://github.com/Dealman/BannerlordModTemplate/releases/tag/1.1.0).

**Comment by RalfKeller** [comment]
Perfect, thank you very much!
