### ISSUE TITLE
Ampersand is not escaped for custom install locations.

### ISSUE THREAD

**Issue by kfedorov** [Dealman/BannerlordModTemplate#6]
Creating new Bannerlord Mod projects fails with an exception relating to the game's installation path. Looking at the code, the '&' is escaped for the default location, but not for the manually specified install path.

**Comment by Dealman** [comment]
Thanks for the report, this will be fixed in the new version!

**Comment by Dealman** [comment]
This should be fixed in [2.0.0](https://github.com/Dealman/BannerlordModTemplate/releases/tag/2.0.0).
